export declare const LIST_TAGS: string[];
export declare const SUPPORTED_CONTAINER_TAGS: string[];
export declare const SUPPORTED_CLICK_INPUT_TYPES: string[];
export declare const SUPPORTED_CHANGE_TYPES: string[];
export declare const SUPPORTED_ICON_TAGS: string[];
export declare const UNSUPPORTED_CLICK_TAGS: string[];
export declare const TEXT_NODE: string[];
export declare const UNSUPPORTED_TAGS: string[];
export declare const EXCLUDE_CLASS_RE: RegExp;
export declare const VALID_ID_SELECTOR: RegExp;
export declare const VALID_CLASS_SELECTOR: RegExp;
export declare const GROWING_IGNORE = "data-growing-ignore";
export declare const GROWING_TRACK = "data-growing-track";
export declare const GROWING_CONTAINER = "data-growing-container";
export declare const GROWING_INDEX = "data-growing-index";
export declare const GROWING_INDEX_OLD = "data-growing-idx";
export declare const GROWING_CDP_INDEX = "data-index";
export declare const GROWING_GTITLE = "data-growing-title";
export declare const GROWING_TITLE = "data-title";
export declare const GROWING_TITLE_OLD = "growing-title";
